### ISSUE TITLE
can download playlist

### ISSUE THREAD

**Issue by JLSkyzer** [Lettly/Youtube-Download-Batch#11]
hello, i have this error
Made with love by Lettly

Enter video url: https://www.youtube.com/playlist?list=OLAK5uy_kY2B_-JTiO3VqrOFiLscGBXCHZDH2OMbM
[youtube:tab] OLAK5uy_kY2B_-JTiO3VqrOFiLscGBXCHZDH2OMbM: Downloading webpage
[download] Downloading playlist: ALT F4
[youtube:tab] playlist ALT F4: Downloading 7 videos
[download] Downloading video 1 of 7
[youtube] pWUPnaSLCFE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Appuyez sur une touche pour continuer...

**Comment by Lettly** [comment]
Have you tried to run the updater, if so, please report this issue on https://yt-dl.org/bug
