### ISSUE TITLE
Any thing link youtube said "Video Not available

### ISSUE THREAD

**Issue by bunty20077** [Lettly/Youtube-Download-Batch#4]
i am trying to download a video using your batch file. Canoot able to do so.. Anything link it is saying "Video not available"

Link : https://www.youtube.com/watch?v=crQcAGNJQtc

**Comment by Lettly** [comment]
Try to run Update.bat first.
If the problem persists you can try opening an issue on https://github.com/ytdl-org/youtube-dl
This is the library that the program uses to download video.
